### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Arkyrie** [Deco71/BasicDiscordMusicBot#1]
when i stop the bot its doing that to me why?

D:\Dev\dfgwretg45wytgwedrtgfdg\venv\lib\site-packages\discord\player.py:616: RuntimeWarning: coroutine 'Command.__call__' was never awaited
  self.after(error)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by Deco71** [comment]
You mean when using the !stop command?
I tried to replicate the error but it never happened to me. 
That error means that you are calling a couroutine (like an async function) without using the "await" before calling it. Have you changed some of the code? If it's that the case, make sure that you use the await where needed.
If instead you haven't touched the code and you can replicate the error, I'll be really grateful if can you give me the exact steps so I can replicate the error myself and try to fix it.

**Comment by Arkyrie** [comment]
Hi I'm sorry to have made you think that there was an error its come from me I modified the code a little I managed to solve it and you did a very good job
